// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbqeboydvyrjmlhhlvme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBicWVib3lkdnlyam1saGhsdm1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjY2MDQsImV4cCI6MjA2NTMwMjYwNH0.c34IZ2JNNlkZ-tA_Z1YYL4_GvBOvrIYZdR_yoWraj4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);